https://www.youtube.com/watch?v=il8dMDlXrIE

In [127]:
import numpy as np
import pandas as pd
from pycaret.classification import *
from PIL import Image
import os
from sklearn.model_selection import train_test_split

In [128]:
input_dir = 'num_data'
categories = ['0', '๑', '๒', '๓', '๔', '๕', '๖', '๗', '๘', '๙']

data = []
labels = []

for category_idx, category in enumerate(categories):
    for file in os.listdir(os.path.join(input_dir, category)):
        img_path = os.path.join(input_dir, category, file)
        img = Image.open(img_path)
        img = img.resize((28, 28))
        img = np.array(img).flatten()
        data.append(img)
        labels.append(category_idx)

data = np.asarray(data)
labels = np.asarray(labels)

In [129]:
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42, stratify=labels)

In [130]:
from sklearn.neural_network import MLPClassifier
NN = MLPClassifier()
NN.fit(x_train, y_train)
y_pred = NN.predict(x_test)

In [131]:
from sklearn.metrics import confusion_matrix, accuracy_score 

accuracy = accuracy_score(y_test,y_pred)*100
confusion_mat = confusion_matrix(y_test,y_pred)

print("Accuracy for Neural Network is:",accuracy)
print("Confusion Matrix")
print(confusion_mat)

Accuracy for Neural Network is: 20.0
Confusion Matrix
[[0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]]


In [132]:
print(y_pred)
print(y_test)

[2 2 0 2 2 3 2 2 3 2]
[4 2 9 0 8 7 6 5 3 1]
